### ISSUE TITLE
Título de archivo erróneo"

### ISSUE THREAD

**Issue by Resaj** [open-robosports/normativa-velocistas#1]
Cambiar "puntacion.md" por "puntuación.md"

**Comment by JavierIH** [comment]
Imagino que te refieres a combate.md por puntuacion.md en el enlace

**Comment by JavierIH** [comment]
ah, puntAcion... me ha costado

![](https://thumbs.gfycat.com/CalculatingPracticalIrishwolfhound-small.gif)
